/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestormuebles.Igu;

import com.mycompany.gestormuebles.Logica.Controlador;
import com.mycompany.gestormuebles.Logica.Proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Jseba
 */
public class EditarProveedor extends javax.swing.JFrame {

    int id_usuario;
    Controlador controlLogica;
    Proveedor proveedor1;
    RegistroProveedor1 recargarPagina;

    /**
     * Creates new form EditarProveedor
     */
    public EditarProveedor(int id_usuario, Controlador controlLogica, RegistroProveedor1 recargarPagina) {
        this.id_usuario = id_usuario;
        this.controlLogica = controlLogica;
        this.recargarPagina = recargarPagina;
        initComponents();
        cargarDatos(id_usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNombreProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtcontactoProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtCorreoProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtTelefonoProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDireccionProveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CmbEstado = new javax.swing.JComboBox<>();
        BtnGuardarProveedor = new javax.swing.JButton();
        BtnLimpiarProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel7.setText("PROVEEDORES ");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("CONTACTO:");

        TxtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreProveedorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        TxtcontactoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcontactoProveedorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("TELEFONO: ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("CORREO ELECTRONICO:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("DIRECCIÓN:");

        TxtDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccionProveedorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("ESTADO:");

        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        CmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbEstadoActionPerformed(evt);
            }
        });

        BtnGuardarProveedor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnGuardarProveedor.setText("GUARDAR");
        BtnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarProveedorActionPerformed(evt);
            }
        });

        BtnLimpiarProveedor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnLimpiarProveedor.setText("LIMPIAR");
        BtnLimpiarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCorreoProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtDireccionProveedor)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtTelefonoProveedor))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtcontactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(55, 55, 55)
                                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnGuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnLimpiarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(290, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(TxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtcontactoProveedor)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpiarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreProveedorActionPerformed

    private void TxtcontactoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcontactoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcontactoProveedorActionPerformed

    private void TxtDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccionProveedorActionPerformed

    private void CmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbEstadoActionPerformed

    private void BtnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarProveedorActionPerformed
        String nombreEp = TxtNombreProveedor.getText();
        String contactoEp = TxtcontactoProveedor.getText();
        String telefonoEp = TxtTelefonoProveedor.getText();
        String direccionEp = TxtDireccionProveedor.getText();
        String correoEp = TxtCorreoProveedor.getText();
        String estadoP = (String) CmbEstado.getSelectedItem();
        if (nombreEp.isEmpty() || contactoEp.isEmpty() || telefonoEp.isEmpty() || direccionEp.isEmpty() || correoEp.isEmpty() || estadoP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por Favor los campos deben estar completados", "Información", JOptionPane.INFORMATION_MESSAGE);

        } else {
            controlLogica.modificarProveedor(proveedor1, nombreEp, contactoEp, telefonoEp, direccionEp, correoEp, estadoP);
            JOptionPane.showMessageDialog(null, "Se guardo correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            recargarPagina.CargarTabla();
            this.dispose();

        }

    }//GEN-LAST:event_BtnGuardarProveedorActionPerformed

    private void BtnLimpiarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarProveedorActionPerformed
        // TODO add your handling code here:
        TxtNombreProveedor.setText("");
        TxtcontactoProveedor.setText("");
        TxtTelefonoProveedor.setText("");
        TxtCorreoProveedor.setText("");
        TxtDireccionProveedor.setText("");
        CmbEstado.setSelectedIndex(0);
    }//GEN-LAST:event_BtnLimpiarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarProveedor;
    private javax.swing.JButton BtnLimpiarProveedor;
    private javax.swing.JComboBox<String> CmbEstado;
    private javax.swing.JTextField TxtCorreoProveedor;
    private javax.swing.JTextField TxtDireccionProveedor;
    private javax.swing.JTextField TxtNombreProveedor;
    private javax.swing.JTextField TxtTelefonoProveedor;
    private javax.swing.JTextField TxtcontactoProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos(int id_usuario) {
        this.proveedor1 = controlLogica.traerProveedores(id_usuario);

        TxtNombreProveedor.setText(proveedor1.getNombreProveedor());
        TxtcontactoProveedor.setText(proveedor1.getContactoProveedor());
        TxtTelefonoProveedor.setText(proveedor1.getTelefonoProveedor());
        TxtCorreoProveedor.setText(proveedor1.getCorreoProveedor());
        TxtDireccionProveedor.setText(proveedor1.getDireccion());

        if (proveedor1.getEstado().equals("ACTIVO")) {
            CmbEstado.setSelectedIndex(0);
        } else {
            CmbEstado.setSelectedItem(1);
        }
    }

    public void MostrarMensaje(String mensaje, String tipoMensaje, String titulo) {
        int tipo = 0;
        if (tipoMensaje.equals("Info")) {
            tipo = JOptionPane.INFORMATION_MESSAGE;
        } else if (tipoMensaje.equals("Error")) {
            tipo = JOptionPane.WARNING_MESSAGE;

        }
        JOptionPane.showMessageDialog(null, mensaje, titulo, tipo);
    }

}
