/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestormuebles.Igu;

import com.mycompany.gestormuebles.Logica.Controlador;
import com.mycompany.gestormuebles.Logica.Materiales;
import com.mycompany.gestormuebles.Logica.Receta;
import com.mycompany.gestormuebles.Logica.Receta_Material;
import com.mycompany.gestormuebles.Logica.ReporteRecetasService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jseba
 */
public class RegistroReceta extends javax.swing.JPanel {

    Controlador controlLogica = new Controlador();
    private List<Materiales> listaMateriales;

    /**
     * Creates new form RegistroReceta
     */
    public RegistroReceta() {
        initComponents();
        // Añadir el listener que carga datos al mostrarse el panel
        this.addAncestorListener(new javax.swing.event.AncestorListener() {
            @Override
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cargarTablas(); // Aquí cargas o refrescas tus datos
            }

            @Override
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }

            @Override
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblMateriales = new javax.swing.JTable();
        BtnRecetasCreadas = new javax.swing.JButton();
        BtnGenerarReporte = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombreReceta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaDescripcion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblMaterialagregado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        BtnAgregarMaterial = new javax.swing.JButton();
        BtnEliminarMaterial = new javax.swing.JButton();
        BtnGuardarReceta = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("LISTA DE MATERIALES");

        TblMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblMateriales);

        BtnRecetasCreadas.setText("Lista de Recetass");
        BtnRecetasCreadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecetasCreadasActionPerformed(evt);
            }
        });

        BtnGenerarReporte.setText("Generar Reporte");
        BtnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(BtnGenerarReporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRecetasCreadas)))
                        .addGap(14, 14, 14))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnRecetasCreadas, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(BtnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel7.setText("CREACIÓN DE RECETAS");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        TxtNombreReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreRecetaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("DESCRIPCIÓN: ");

        TxtAreaDescripcion.setColumns(20);
        TxtAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxtAreaDescripcion);

        TblMaterialagregado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TblMaterialagregado);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("MATERIALES AGREGADOS:");

        BtnAgregarMaterial.setText("Agregar ");
        BtnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarMaterialActionPerformed(evt);
            }
        });

        BtnEliminarMaterial.setText("Eliminar");
        BtnEliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarMaterialActionPerformed(evt);
            }
        });

        BtnGuardarReceta.setText("Guardar");
        BtnGuardarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(78, 78, 78))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(BtnAgregarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnGuardarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtNombreReceta))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGuardarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreRecetaActionPerformed

    private void BtnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarMaterialActionPerformed
        // TODO add your handling code here:
        AgregarMaterialReceta agregarMaterial = new AgregarMaterialReceta(this);
        agregarMaterial.setVisible(true);
        agregarMaterial.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnAgregarMaterialActionPerformed

    private void BtnGuardarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarRecetaActionPerformed
        // TODO add your handling code here:
        String nombreReceta = TxtNombreReceta.getText();
        String descripcionReceta = TxtAreaDescripcion.getText();

        if (nombreReceta.isEmpty() || descripcionReceta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }

        Receta receta = new Receta();
        receta.setNombreReceta(nombreReceta);
        receta.setDescripcionReceta(descripcionReceta);
        controlLogica.guardarReceta(receta);

        DefaultTableModel modelo = (DefaultTableModel) TblMaterialagregado.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            int idmaterial = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 3).toString());

            Materiales mat = controlLogica.traerMaterial(idmaterial);

            if (mat != null) {
                Receta_Material recetaMaterial = new Receta_Material();
                recetaMaterial.setRecetaMaterial(receta);
                recetaMaterial.setMaterialReceta(mat);
                recetaMaterial.setCantidad(cantidad);
                controlLogica.guardarRecetaMaterial(recetaMaterial);
            }
        }
        JOptionPane.showMessageDialog(null, "Receta registrada exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        limpiarDatos();
    }//GEN-LAST:event_BtnGuardarRecetaActionPerformed

    private void BtnEliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarMaterialActionPerformed
        // TODO add your handling code here:
        if (TblMaterialagregado.getRowCount() > 0) {
            if (TblMaterialagregado.getSelectedRow() != -1) {
                DefaultTableModel modelo = (DefaultTableModel) TblMaterialagregado.getModel();
                modelo.removeRow(TblMaterialagregado.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Material eliminado de la receta.");
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un material para eliminar.");

            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay materiales para eliminar.");

        }
    }//GEN-LAST:event_BtnEliminarMaterialActionPerformed

    private void BtnRecetasCreadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecetasCreadasActionPerformed
        // TODO add your handling code here:
       ListaDeRecetas listarecetas = new ListaDeRecetas();
       listarecetas.setVisible(true);
       listarecetas.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnRecetasCreadasActionPerformed

    private void BtnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarReporteActionPerformed
        try {
        // Obtener todas las recetas usando tu controlador de lógica
        List<Receta> recetas = controlLogica.traerRecetas();

        // Crear instancia del servicio de reporte
        ReporteRecetasService reporteService = new ReporteRecetasService();

        // Generar PDF en bytes
        byte[] pdf = reporteService.generarReporteRecetas(recetas, "Robert Sulca");

        // Guardar el PDF en disco (puedes cambiar la ruta o nombre)
        java.nio.file.Path path = java.nio.file.Paths.get("reporte_recetas.pdf");
        java.nio.file.Files.write(path, pdf);

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Reporte generado correctamente en:\n" + path.toAbsolutePath());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_BtnGenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarMaterial;
    private javax.swing.JButton BtnEliminarMaterial;
    private javax.swing.JButton BtnGenerarReporte;
    private javax.swing.JButton BtnGuardarReceta;
    private javax.swing.JButton BtnRecetasCreadas;
    private javax.swing.JTable TblMaterialagregado;
    private javax.swing.JTable TblMateriales;
    private javax.swing.JTextArea TxtAreaDescripcion;
    private javax.swing.JTextField TxtNombreReceta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    void cargarTablas() {
        cargarTablaAgregados();
        cargarTablaMaterial();
    }

    void cargarTablaAgregados() {
        //Definir Modelo de la tabla y que las columnas no sean editables
        DefaultTableModel tabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return true;
            }
        };

        //Creacion de los nombres de la columna
        String titulos[] = {"ID", "Nombre", "Categoria", "Cantidad"};
        tabla.setColumnIdentifiers(titulos);

        TblMaterialagregado.setModel(tabla);
        //Cargar los datos
        //List<Materiales> listaMateriales = controlLogica.traerMateriales();
    }

    public void agregarMaterial(Materiales material, int cantidad) {
        DefaultTableModel modelo = (DefaultTableModel) TblMaterialagregado.getModel();
        modelo.addRow(new Object[]{
            material.getIdMaterial(), material.getNombreMaterial(), material.getCategoriaMaterial().getNombreCategoria(), cantidad
        });

    }

    private void cargarTablaMaterial() {
        DefaultTableModel tablaMateriales = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String TItulosMateriales[] = {"ID", "Nombre", "Categoria", "Cantidad"};
        tablaMateriales.setColumnIdentifiers(TItulosMateriales);

        listaMateriales = controlLogica.traerMateriales();

        if (listaMateriales != null) {
            for (Materiales materiales : listaMateriales) {
                Object[] objecto = {materiales.getIdMaterial(), materiales.getNombreMaterial(), materiales.getCategoriaMaterial().getNombreCategoria(), materiales.getCantidadMaterial()};
                tablaMateriales.addRow(objecto);
            }
        }
        TblMateriales.setModel(tablaMateriales);

    }

    private void limpiarDatos() {
        TxtNombreReceta.setText("");
        TxtAreaDescripcion.setText("");
        DefaultTableModel modelo = (DefaultTableModel) TblMaterialagregado.getModel();
        modelo.setRowCount(0);
    }
}
