/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestormuebles.Igu;

import com.mycompany.gestormuebles.Logica.CategoriaMaterial;
import com.mycompany.gestormuebles.Logica.Controlador;
import com.mycompany.gestormuebles.Logica.Materiales;
import com.mycompany.gestormuebles.Logica.Proveedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jseba
 */
public class RegistroMaterial1 extends javax.swing.JPanel {

    Controlador controlLogica = new Controlador();

    /**
     * Creates new form RegistroMaterial1
     */
    public RegistroMaterial1() {
        initComponents();
        this.addAncestorListener(new javax.swing.event.AncestorListener() {
            @Override
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CargarDatos();
                cargarTabla();

            }

            @Override
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }

            @Override
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorMaterial = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDatosMateriales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        BtnEliminarMaterial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNombreMateriales = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbxCategoriaMaterial = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        TxtCantidadMateriales = new javax.swing.JTextField();
        BtnRegistrarMaterial = new javax.swing.JButton();
        CbxProveedorMaterial = new javax.swing.JComboBox<>();
        BtnLimpiar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TblDatosMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblDatosMateriales);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LISTA DE MATERIALES");

        BtnEditar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnEditar.setText("EDITAR");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminarMaterial.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnEliminarMaterial.setText("ELIMINAR");
        BtnEliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("REGISTRO DE MATERIALES");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("NOMBRE:");

        TxtNombreMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreMaterialesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("PROVEEDOR:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("CATEGORIA:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("CANTIDAD:");

        TxtCantidadMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadMaterialesActionPerformed(evt);
            }
        });

        BtnRegistrarMaterial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BtnRegistrarMaterial.setText("Registrar");
        BtnRegistrarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarMaterialActionPerformed(evt);
            }
        });

        BtnLimpiar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCantidadMateriales)
                            .addComponent(TxtNombreMateriales)
                            .addComponent(CbxCategoriaMaterial, 0, 209, Short.MAX_VALUE)
                            .addComponent(CbxProveedorMaterial, 0, 209, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnRegistrarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbxProveedorMaterial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CbxCategoriaMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(TxtCantidadMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistrarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout ContenedorMaterialLayout = new javax.swing.GroupLayout(ContenedorMaterial);
        ContenedorMaterial.setLayout(ContenedorMaterialLayout);
        ContenedorMaterialLayout.setHorizontalGroup(
            ContenedorMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ContenedorMaterialLayout.setVerticalGroup(
            ContenedorMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorMaterialLayout.createSequentialGroup()
                .addGroup(ContenedorMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenedorMaterialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        if (TblDatosMateriales.getRowCount() > 0) {
            if (TblDatosMateriales.getSelectedRow() != -1) {
                int id_Material = Integer.parseInt(String.valueOf(TblDatosMateriales.getValueAt(TblDatosMateriales.getSelectedRow(), 0)));
                EditarMaterial editarMaterial = new EditarMaterial(id_Material, controlLogica, this);
                editarMaterial.setVisible(true);
                editarMaterial.setLocationRelativeTo(null);
            } else {
                MostrarMensaje("No se selecciono a un elemento a borrar", "Error", "Error");

            }
        } else {
            MostrarMensaje("La tabla no tiene datos", "Error", "Error");

        }
        cargarTabla();
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnEliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarMaterialActionPerformed
        if (TblDatosMateriales.getRowCount() > 0) {
            if (TblDatosMateriales.getSelectedRow() != -1) {
                int id_Material = Integer.parseInt(String.valueOf(TblDatosMateriales.getValueAt(TblDatosMateriales.getSelectedRow(), 0)));
                controlLogica.eliminarMaterial(id_Material);
                MostrarMensaje("Se borro correctamente", "Info", "Eliminar");
                cargarTabla();
            } else {
                MostrarMensaje("No se selecciono a un elemento a borrar", "Error", "Error");

            }
        } else {
            MostrarMensaje("La tabla no tiene datos", "Error", "Error");

        }
        cargarTabla();
    }//GEN-LAST:event_BtnEliminarMaterialActionPerformed

    private void TxtNombreMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreMaterialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreMaterialesActionPerformed

    private void TxtCantidadMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadMaterialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadMaterialesActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        TxtNombreMateriales.setText("");
        CbxProveedorMaterial.setSelectedIndex(0);
        CbxCategoriaMaterial.setSelectedIndex(0);
        TxtCantidadMateriales.setText("");
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnRegistrarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarMaterialActionPerformed
        // TODO add your handling code here:

        String Nombrematerial = TxtNombreMateriales.getText();
        String proveedor = (String) CbxProveedorMaterial.getSelectedItem();
        String categoria = (String) CbxCategoriaMaterial.getSelectedItem();
        String cantidad = TxtCantidadMateriales.getText();

        if (Nombrematerial.isEmpty() || proveedor.isEmpty() || categoria.isEmpty() || cantidad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por Favor los campos deben estar completados", "Información", JOptionPane.INFORMATION_MESSAGE);

        } else {
            int cantidadf;
            cantidadf = Integer.parseInt(cantidad);
            controlLogica.guardarMaterial(Nombrematerial, proveedor, categoria, cantidadf);
            JOptionPane.showMessageDialog(null, "Se guardó correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            CargarDatos();
        }

    }//GEN-LAST:event_BtnRegistrarMaterialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminarMaterial;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRegistrarMaterial;
    private javax.swing.JComboBox<String> CbxCategoriaMaterial;
    private javax.swing.JComboBox<String> CbxProveedorMaterial;
    private javax.swing.JPanel ContenedorMaterial;
    private javax.swing.JTable TblDatosMateriales;
    private javax.swing.JTextField TxtCantidadMateriales;
    private javax.swing.JTextField TxtNombreMateriales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void CargarDatos() {
        cargarProveedor();
        cargarCategoria();
    }

    private void cargarProveedor() {
        List<Proveedor> listaproveedor = controlLogica.traerProveedores();
        if (listaproveedor != null) {
            for (Proveedor proveedor : listaproveedor) {
                CbxProveedorMaterial.addItem(proveedor.getNombreProveedor());
            }
        }
    }

    void cargarTabla() {
        //Definir Modelo de la tabla y que las columnas no sean editables
        DefaultTableModel tabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //Creacion de los nombres de la columna
        String titulos[] = {"ID", "Nombre", "Categoria", "Proveedor", "Cantidad"};
        tabla.setColumnIdentifiers(titulos);

        //Cargar los datos
        List<Materiales> listaMateriales = controlLogica.traerMateriales();

        //Recorrer la lista
        if (listaMateriales != null) {
            for (Materiales materiales : listaMateriales) {
                Object[] objeto = {materiales.getIdMaterial(), materiales.getNombreMaterial(), materiales.getCategoriaMaterial().getNombreCategoria(), materiales.getMaterialProveedor().getNombreProveedor(), materiales.getCantidadMaterial()};
                tabla.addRow(objeto);
            }
        }
        TblDatosMateriales.setModel(tabla);
    }

    private void cargarCategoria() {
        List<CategoriaMaterial> listaCategoria = controlLogica.traerCatogorias();
        if (listaCategoria != null) {
            for (CategoriaMaterial categoriaMaterial : listaCategoria) {
                CbxCategoriaMaterial.addItem(categoriaMaterial.getNombreCategoria());
            }
        }
    }

    public void MostrarMensaje(String mensaje, String tipoMensaje, String titulo) {
        int tipo = 0;
        if (tipoMensaje.equals("Info")) {
            tipo = JOptionPane.INFORMATION_MESSAGE;
        } else if (tipoMensaje.equals("Error")) {
            tipo = JOptionPane.WARNING_MESSAGE;

        }
        JOptionPane.showMessageDialog(null, mensaje, titulo, tipo);
    }
}
