name: CI/CD - Compilar y desplegar JAR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar proyecto
        run: mvn clean compile

      - name: Ejecutar pruebas
        run: mvn test

      - name: Construir JAR
        run: mvn package

      - name: Subir JAR a rama deploy-artifacts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          mkdir temp-folder
          cp target/*.jar temp-folder/

          git fetch origin
          git switch --orphan deploy-artifacts
          git rm -rf .

          cp temp-folder/*.jar .
          git add *.jar
          git commit -m "Deploy automático del JAR"
          git push --force origin deploy-artifacts
